baseURL: http://localhost
# Disable taxonomy pages (disables categories and tags folders)
disableKinds:
  - taxonomy
  - taxonomyTerm
# for xml output
languageCode: en
# for website
defaultContentLanguage: en
title: FriedFireAnt
# alternate copyright company text
copyright: FriedFireAnt
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7
# Allow html in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
