baseURL: http://localhost
# Disable taxonomy pages (disables categories and tags folders)
disableKinds:
- taxonomy
- taxonomyTerm
# for xml output
languageCode: "en-au"
# for website
defaultContentLanguage: "en-au"
languages:
  en-au:
    weight: 1
title: FriedFireAnt
# alternate copyright company text
copyright: FriedFireAnt
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7

# Allow html in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true

# menu links via config file
# menu:
#   main:
#   - identifier: "about"
#     name: "About Me"
#     url: "/about"
#     weight: 21
#   - name: Google
#     url: http://www.google.com/
#     weight: 100
#     params:
#       blank: true