backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where the users uploaded files should go
public_folder: "/img" # the folder that shows up in the public url: url.com/img
logo_url: https://friedfireant.netlify.app/img/logo.webp
collections:
  - name: "About"
    label: "About"
    files:
      - file: "content/about.md"
        label: "Page Content"
        name: "Page Content"
        fields:
          - { label: "Title", name: "title", widget: "string" } # The title of the page
          - { label: "Heading", name: "heading", widget: "text" } # The heading title of the about me page
          - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
          - { label: "Selfportrait", name: "selfportrait", widget: "image" }
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    extension: "json"
    files:
      - name: "portfolioList"
        label: "Images"
        file: "/data/portfolio.json"
        fields:
          - name: portfolioList
            label: Portfolio images
            widget: list
            summary: "{{fields.src}} - {{fields.class}}"
            label_singular: "new work"
            add_to_top: true
            fields:
              - {
                  label: "Type Art",
                  name: "class",
                  widget: "select",
                  options:
                    [
                      "character-art",
                      "studies",
                      "concept-art",
                      "paintings",
                      "other",
                    ],
                }
              - { label: "Image", name: "src", widget: "image" }
  - name: "commissions"
    label: "Commissions"
    files:
      - name: "commissionsList"
        label: "Images"
        format: "json"
        extension: "json"
        file: "/data/commissions.json"
        fields:
          - name: commissionsList
            label: Commission images
            widget: list
            summary: "{{fields.src}}"
            label_singular: "new commission"
            add_to_top: true
            fields:
              - { label: "Image", name: "src", widget: "image" }
      - label: "Page Content"
        name: "commissions"
        fields:
          - file: "content/commissions/index.md"
            label: "Commissions Open?"
            name: "commissionsopen"
            widget: boolean
          - file: "content/commissions/commissionsopen.md"
            label: "Commissions Open Text"
            name: "body"
            widget: markdown
          - file: "content/commissions/commissionsclosed.md"
            label: "Commissions Closed Text"
            name: "body2"
            widget: markdown
      # - file: "content/commissions/index.md"
      #   label: "Page Content"
      #   name: "commissions"
      #   fields:
      #     - label: "Commissions Open?"
      #       name: "commissionsopen"
      #       widget: boolean
      #     - file: "content/commissions/commissionsopen.md"
      #       label: "Commissions Open Text"
      #       name: "body"
      #       widget: markdown
      #     - file: "content/commissions/commissionsclosed.md"
      #       label: "Commissions Closed Text"
      #       name: "body2"
      #       widget: markdown
              
          # - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
  - name: "Website Settings"
    label: "Website Settings"
    files:
      - name: general
        label: Website Settings
        file: "data/settings/general.yml"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Styling"
            name: "styling"
            widget: "object"
            fields:
              - { label: "Primary Color", name: "primarycolor", default: "#c4437d", widget: "color" }
              - { label: "Title Color", name: "titlecolor", default: "#141313", widget: "color" }
              - { label: "Text Color", name: "textcolor", default: "#777777", widget: "color" }
              - widget: "select" 
                label: "Font"
                name: "font"
                default: ["menlotus"]
                options: ["menlotus", "alone-on-earth", "traho"]
