backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where the users uploaded files should go
public_folder: "/img" # the folder that shows up in the public url: url.com/img
logo_url: https://friedfireant.netlify.app/img/logo.webp
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" } # The title of the page
          - { label: "Heading", name: "heading", widget: "text" } # The heading title of the about me page
          - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    extension: "json"
    files:
      - name: "portfolioList"
        label: "Images"
        file: "/data/portfolio.json"
        fields:
          - name: portfolioList
            label: Portfolio images
            widget: list
            summary: "{{fields.src}} - {{fields.class}}"
            label_singular: "new work"
            add_to_top: true
            fields:
              - {
                  label: "Type Art",
                  name: "class",
                  widget: "select",
                  options:
                    [
                      "character-art",
                      "studies",
                      "concept-art",
                      "paintings",
                      "other",
                    ],
                }
              - { label: "Image", name: "src", widget: "image" }
  - name: "commissions"
    label: "Commissions"
    files:
      - name: "commissionsList"
        label: "Images"
        format: "json"
        extension: "json"
        file: "/data/commissions.json"
        fields:
          - name: commissionsList
            label: Commission images
            widget: list
            summary: "{{fields.src}}"
            label_singular: "new commission"
            add_to_top: true
            fields:
              - { label: "Image", name: "src", widget: "image" }
      - file: "content/commissions/index.md"
        label: "Page Content"
        name: "Commissions text content"
        fields:
          - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
  - name: "Website Settings"
    label: "Website Settings"
    files:
      - name: general
        label: Website Settings
        file: "data/settings/general.yml"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
