backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where the users uploaded files should go
public_folder: "/img" # the folder that shows up in the public url: url.com/img
logo_url: https://friedfireant.netlify.app/img/logo.webp
collections:
  - name: "About"
    label: "About"
    files:
      - file: "content/about.md"
        label: "Page Content"
        name: "Page Content"
        fields:
          - { label: "Title", name: "title", widget: "string" } # The title of the page
          - { label: "Heading", name: "heading", widget: "text" } # The heading title of the about me page
          - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
          - { label: "Selfportrait", name: "selfportrait", widget: "image" }
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    extension: "json"
    files:
      - name: "portfolioList"
        label: "Images"
        file: "/data/portfolio.json"
        fields:
          - name: portfolioList
            label: Portfolio images
            widget: list
            summary: "{{fields.src}} - {{fields.class}}"
            label_singular: "new work"
            add_to_top: true
            fields:
              - {
                  name: 'class',
                  label: 'Type Art',
                  widget: 'create-select',
                  url: 'https://friedfireant.netlify.app/portfolio/',
                  query: "#myBtnContainer > button",
                  mode: 'html',
                  multiple: false,
                  min: 1,
                  attribute: 'data-tag',
                  hint: "New categories should be created with '-' instead of spaces"
                }
              - { label: "Image", name: "src", widget: "image" }
  - name: "commissions"
    label: "Commissions"
    files:
      - name: "commissionsList"
        label: "Images"
        format: "json"
        extension: "json"
        file: "/data/commissions.json"
        fields:
          - name: commissionsList
            label: Commission images
            widget: list
            summary: "{{fields.src}}"
            label_singular: "new commission"
            add_to_top: true
            fields:
              - { label: "Image", name: "src", widget: "image" }
      - file: "content/commissions/index.md"
        name: "togglecommissions"
        label: "Toggle Commissions"
        fields:
          - {label: "Commissions Open?", name: "commissionsopen", hint: "Blue toggle means that the commissions are open", widget: boolean}
      - file: "content/commissions/commissionsopen.md"
        name: "commissionsopentext"
        label: "Commissions Open Text"
        fields: 
          - {label: "Commissions Open Text", name: "body", widget: markdown}
      - file: "content/commissions/commissionsclosed.md"
        name: "commissionsclosedtext"
        label: "Commissions Closed Text"
        fields: 
         - {label: "Commissions Closed Text", name: "body", widget: markdown}

      # - file: "content/commissions/index.md"
      #   label: "Page Content"
      #   name: "commissions"
      #   fields:
      #     - label: "Commissions Open?"
      #       name: "commissionsopen"
      #       widget: boolean
      #     - file: "content/commissions/commissionsopen.md"
      #       label: "Commissions Open Text"
      #       name: "body"
      #       widget: markdown
      #     - file: "content/commissions/commissionsclosed.md"
      #       label: "Commissions Closed Text"
      #       name: "body2"
      #       widget: markdown
              
          # - { label: "Body", name: "body", widget: "text" } # The content of the markdown file
  - name: "Website Settings"
    label: "Website Settings"
    files:
      - name: general
        label: Website Settings
        file: "data/settings/general.yml"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - label: "Styling"
            name: "styling"
            widget: "object"
            fields:
              - { label: "Primary Color", name: "primarycolor", hint: "Default value is #c4437d\nThis color is primarily used for navbar items and the filters", widget: "color" }
              - { label: "Title Color", name: "titlecolor", hint: "Default value is #333333\nThis color is for the page titles", widget: "color" }
              - { label: "Text Color", name: "textcolor", hint: "Default value is #777777\nThis color is for text on pages", widget: "color" }
              - widget: "select" 
                label: "Font"
                name: "font"
                default: ["menlotus"]
                options: ["menlotus", inter]
